import crypto from 'crypto';
import { adminPool } from '../../db/pool';

export interface DeviceRegistrationInput {
  phcId:      string;
  deviceName: string;
  publicKey?: string; // Optional client-supplied public key; if omitted, backend generates a key pair
  metadata?:  Record<string, unknown>;
}

export interface DeviceRegistrationResult {
  deviceId:          string;
  phcId:             string;
  deviceName:        string;
  publicKey:         string;
  privateKey?:       string; // Returned only if generated by server on initial registration
  deviceFingerprint: string;
  status:            'active' | 'revoked' | 'pending';
  registeredAt:      string;
}

export class DeviceService {
  /**
   * Registers a new device bound to a specific PHC.
   * If client doesn't provide a public key, generates an RSA-2048 keypair.
   */
  static async registerDevice(input: DeviceRegistrationInput): Promise<DeviceRegistrationResult> {
    let publicKey = input.publicKey;
    let privateKey: string | undefined;

    if (!publicKey) {
      const keypair = crypto.generateKeyPairSync('rsa', {
        modulusLength: 2048,
        publicKeyEncoding: { type: 'spki', format: 'pem' },
        privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
      });
      publicKey = keypair.publicKey;
      privateKey = keypair.privateKey;
    }

    // Compute SHA-256 fingerprint from public key
    const fingerprint = crypto.createHash('sha256').update(publicKey).digest('hex');

    // Check if PHC facility exists
    const facilityCheck = await adminPool.query(`SELECT id FROM phc_facilities WHERE id = $1`, [input.phcId]);
    if (facilityCheck.rowCount === 0) {
      throw new Error(`PHC facility not found: ${input.phcId}`);
    }

    // Check for existing fingerprint
    const existing = await adminPool.query(
      `SELECT device_id FROM phc_device_registry WHERE device_fingerprint = $1`,
      [fingerprint],
    );
    if ((existing.rowCount ?? 0) > 0) {
      throw new Error('DEVICE_ALREADY_REGISTERED');
    }

    const insertRes = await adminPool.query(
      `INSERT INTO phc_device_registry (
         phc_id, device_name, device_fingerprint, public_key, status, metadata
       ) VALUES ($1, $2, $3, $4, 'active', $5)
       RETURNING device_id, phc_id, device_name, public_key, device_fingerprint, status, registered_at`,
      [input.phcId, input.deviceName, fingerprint, publicKey, JSON.stringify(input.metadata || {})],
    );

    const row = insertRes.rows[0];
    return {
      deviceId:          row.device_id,
      phcId:             row.phc_id,
      deviceName:        row.device_name,
      publicKey:         row.public_key,
      privateKey,
      deviceFingerprint: row.device_fingerprint,
      status:            row.status,
      registeredAt:      row.registered_at.toISOString(),
    };
  }

  /**
   * Verifies that a device is valid, active, bound to the specified PHC,
   * and that the signature over the payload is cryptographically sound.
   */
  static async verifyDeviceBinding(
    deviceId:  string,
    phcId:     string,
    payload:   string,
    signature: string,
  ): Promise<{ valid: boolean; reason?: string }> {
    const res = await adminPool.query(
      `SELECT device_id, phc_id, public_key, status
       FROM phc_device_registry
       WHERE device_id = $1`,
      [deviceId],
    );

    if (res.rowCount === 0) {
      return { valid: false, reason: 'DEVICE_NOT_FOUND' };
    }

    const device = res.rows[0];

    if (device.status !== 'active') {
      return { valid: false, reason: `DEVICE_STATUS_${device.status.toUpperCase()}` };
    }

    // Strict PHC binding check: device must belong to this exact PHC
    if (device.phc_id !== phcId) {
      return { valid: false, reason: 'DEVICE_PHC_MISMATCH' };
    }

    // Verify signature using the stored public key
    try {
      const verifier = crypto.createVerify('SHA256');
      verifier.update(payload);
      verifier.end();

      const isValid = verifier.verify(device.public_key, signature, 'base64');
      if (!isValid) {
        return { valid: false, reason: 'INVALID_SIGNATURE' };
      }

      // Update last_seen_at asynchronously
      adminPool.query(`UPDATE phc_device_registry SET last_seen_at = NOW() WHERE device_id = $1`, [deviceId])
        .catch(() => {});

      return { valid: true };
    } catch (err: any) {
      return { valid: false, reason: `SIGNATURE_VERIFICATION_ERROR: ${err.message}` };
    }
  }

  /**
   * Helper to sign a payload with a private key (used by clients / tests)
   */
  static signPayload(payload: string, privateKeyPem: string): string {
    const signer = crypto.createSign('SHA256');
    signer.update(payload);
    signer.end();
    return signer.sign(privateKeyPem, 'base64');
  }

  /**
   * Revoke device
   */
  static async revokeDevice(deviceId: string): Promise<boolean> {
    const res = await adminPool.query(
      `UPDATE phc_device_registry SET status = 'revoked' WHERE device_id = $1`,
      [deviceId],
    );
    return (res.rowCount ?? 0) > 0;
  }
}
