// ─────────────────────────────────────────────────────────────────────────────
// Audit Log Seed Data & Generator
// Masterplan §69 compliant: actor_id, actor_role, action, entity_type,
// entity_id, before_state/after_state, created_at, source_ip, device_id,
// correlation_id, ai_rec_payload, scoped by phc_id/district_id/state_id.
// ─────────────────────────────────────────────────────────────────────────────
import { AuditEntry } from '@/types';

export const INITIAL_AUDIT_LOG: AuditEntry[] = [
  {
    auditId: 'aud-20260916-001',
    action: 'threshold.updated',
    entityType: 'governance_config',
    entityId: 'cfg-thresholds-v3.4.1',
    actorId: 'usr-nat-001',
    actorRole: 'national_admin',
    userName: 'Dr. Rajesh Kumar',
    userId: 'usr-nat-001',
    userRole: 'national_admin',
    createdAt: '2026-09-16T17:45:10.000Z',
    timestamp: '2026-09-16T17:45:10.000Z',
    sourceIp: '14.139.122.45',
    ipAddress: '14.139.122.45',
    deviceId: 'GOV-SEC-INSP-MAC-98A1',
    correlationId: 'corr-cfg-9812401',
    stateId: null,
    districtId: null,
    phcId: null,
    beforeState: {
      minimum_stock_days: 21,
      critical_stock_days: 7,
      near_expiry_period_days: 90,
      safety_buffer_pct: 15,
      version: 'v3.4.0',
    },
    afterState: {
      minimum_stock_days: 21,
      critical_stock_days: 7,
      near_expiry_period_days: 90,
      safety_buffer_pct: 18,
      version: 'v3.4.1',
      change_justification: 'Monsoon seasonal disease spike buffer augmentation (MOHFW Memo 8492)',
    },
    aiRecPayload: {
      model: 'ResourceOptimizer-v4',
      suggestedBuffer: 18.5,
      confidence: 0.94,
      rationale: 'Monsoon dengue and malaria caseload forecast exceeds 3-year baseline by 24%',
    },
    metadata: { reason: 'Monsoon seasonal disease spike buffer augmentation (MOHFW Memo 8492)' },
  },
  {
    auditId: 'aud-20260916-002',
    action: 'redistribution.approved',
    entityType: 'redistribution_recommendation',
    entityId: 'rec-pune-701',
    actorId: 'usr-dist-002',
    actorRole: 'district_admin',
    userName: 'Suresh Iyer (Pune)',
    userId: 'usr-dist-002',
    userRole: 'district_admin',
    createdAt: '2026-09-16T16:30:22.000Z',
    timestamp: '2026-09-16T16:30:22.000Z',
    sourceIp: '115.112.44.18',
    ipAddress: '115.112.44.18',
    deviceId: 'DIST-OFFICE-WS-04',
    correlationId: 'corr-redist-771890',
    stateId: 'state-mh',
    districtId: 'dist-pune',
    phcId: 'phc-pune-04',
    beforeState: {
      recommendationId: 'rec-pune-701',
      status: 'pending',
      quantity: 450,
      medicineName: 'Amoxicillin 500mg',
      fromPhcId: 'phc-pune-01',
      toPhcId: 'phc-pune-04',
    },
    afterState: {
      recommendationId: 'rec-pune-701',
      status: 'approved',
      quantity: 450,
      transferStatus: 'approved',
      approvedBy: 'Suresh Iyer',
    },
    aiRecPayload: {
      model: 'RedistributeNet-v2.1',
      sourceSurplusDays: 28,
      destinationDeficitDays: 2.1,
      distanceKm: 18.4,
      transitTimeMinutes: 42,
      preventedStockouts: 1,
    },
    metadata: { notes: 'Approved for urgent morning dispatch' },
  },
  {
    auditId: 'aud-20260916-003',
    action: 'redistribution.modified',
    entityType: 'redistribution_recommendation',
    entityId: 'rec-pune-702',
    actorId: 'usr-dist-002',
    actorRole: 'district_admin',
    userName: 'Suresh Iyer (Pune)',
    userId: 'usr-dist-002',
    userRole: 'district_admin',
    createdAt: '2026-09-16T15:12:00.000Z',
    timestamp: '2026-09-16T15:12:00.000Z',
    sourceIp: '115.112.44.18',
    ipAddress: '115.112.44.18',
    deviceId: 'DIST-OFFICE-WS-04',
    correlationId: 'corr-redist-771891',
    stateId: 'state-mh',
    districtId: 'dist-pune',
    phcId: 'phc-pune-02',
    beforeState: {
      recommendationId: 'rec-pune-702',
      status: 'pending',
      originalQuantity: 300,
      medicineName: 'Paracetamol 500mg',
    },
    afterState: {
      recommendationId: 'rec-pune-702',
      status: 'modified',
      modifiedQuantity: 200,
      modificationReason: 'Source PHC expecting higher weekend OPD footfall',
    },
    aiRecPayload: {
      model: 'RedistributeNet-v2.1',
      originalQuantity: 300,
      recommendedBenefit: 'Averts 5 days shortage',
    },
    metadata: { notes: 'Source PHC expecting higher weekend OPD footfall' },
  },
  {
    auditId: 'aud-20260916-004',
    action: 'crisis_mode.activated',
    entityType: 'system_mode',
    entityId: 'mode-national-crisis',
    actorId: 'usr-nat-001',
    actorRole: 'national_admin',
    userName: 'Dr. Rajesh Kumar',
    userId: 'usr-nat-001',
    userRole: 'national_admin',
    createdAt: '2026-09-16T14:05:44.000Z',
    timestamp: '2026-09-16T14:05:44.000Z',
    sourceIp: '14.139.122.45',
    ipAddress: '14.139.122.45',
    deviceId: 'GOV-SEC-INSP-MAC-98A1',
    correlationId: 'corr-crisis-activation-001',
    stateId: null,
    districtId: null,
    phcId: null,
    beforeState: {
      crisisMode: false,
      activeEmergencies: 3,
      alertLevel: 'elevated',
    },
    afterState: {
      crisisMode: true,
      reason: 'Regional respiratory illness surge in western corridor',
      emergencyId: 'EMG-NAT-2026-04',
      prioritizationRouting: 'critical_first',
    },
    aiRecPayload: {
      model: 'EpidemicEarlyWarning-v3',
      anomalyScore: 4.12,
      footfallSpikePct: 182,
      recommendation: 'Immediate activation of national surge protocols and inter-district supply routing',
    },
    metadata: { reason: 'Regional respiratory illness surge in western corridor' },
  },
  {
    auditId: 'aud-20260916-005',
    action: 'alert.acknowledged',
    entityType: 'early_warning_alert',
    entityId: 'alt-mh-pune-991',
    actorId: 'usr-dist-002',
    actorRole: 'district_admin',
    userName: 'Suresh Iyer (Pune)',
    userId: 'usr-dist-002',
    userRole: 'district_admin',
    createdAt: '2026-09-16T12:20:15.000Z',
    timestamp: '2026-09-16T12:20:15.000Z',
    sourceIp: '115.112.44.18',
    ipAddress: '115.112.44.18',
    deviceId: 'DIST-OFFICE-WS-04',
    correlationId: 'corr-alt-ack-9912',
    stateId: 'state-mh',
    districtId: 'dist-pune',
    phcId: 'phc-pune-03',
    beforeState: {
      alertId: 'alt-mh-pune-991',
      acknowledged: false,
      severity: 'critical',
      alertClass: 'immediate_deterministic',
      metric: 'oxygen_critical_threshold',
      currentValue: '0.8 days',
    },
    afterState: {
      alertId: 'alt-mh-pune-991',
      acknowledged: true,
      acknowledgedAt: '2026-09-16T12:20:15.000Z',
      acknowledgedBy: 'Suresh Iyer',
    },
    aiRecPayload: null,
    metadata: { reason: 'Emergency oxygen cylinder refill van dispatched from Pune CHC' },
  },
  {
    auditId: 'aud-20260916-006',
    action: 'threshold.updated',
    entityType: 'governance_config',
    entityId: 'cfg-thresholds-v3.4.0',
    actorId: 'usr-state-001',
    actorRole: 'state_admin',
    userName: 'Smt. Priya Sharma (MH)',
    userId: 'usr-state-001',
    userRole: 'state_admin',
    createdAt: '2026-09-16T11:00:30.000Z',
    timestamp: '2026-09-16T11:00:30.000Z',
    sourceIp: '103.24.188.12',
    ipAddress: '103.24.188.12',
    deviceId: 'MH-DIRECTORATE-TB-02',
    correlationId: 'corr-cfg-state-8821',
    stateId: 'state-mh',
    districtId: null,
    phcId: null,
    beforeState: {
      bed_occupancy_threshold_pct: 90.0,
      stateId: 'state-mh',
    },
    afterState: {
      bed_occupancy_threshold_pct: 92.0,
      stateId: 'state-mh',
      reason: 'State Health Council revised threshold for tertiary referral escalation',
    },
    aiRecPayload: {
      model: 'BedCapacityPredictor',
      simulatedEscalationsReduction: '-14%',
      riskProfile: 'acceptable',
    },
    metadata: { reason: 'State Health Council revised threshold for tertiary referral escalation' },
  },
  {
    auditId: 'aud-20260916-007',
    action: 'report.exported',
    entityType: 'statutory_report',
    entityId: 'rep-st-mh-2026-q3',
    actorId: 'usr-state-001',
    actorRole: 'state_admin',
    userName: 'Smt. Priya Sharma (MH)',
    userId: 'usr-state-001',
    userRole: 'state_admin',
    createdAt: '2026-09-16T09:40:02.000Z',
    timestamp: '2026-09-16T09:40:02.000Z',
    sourceIp: '103.24.188.12',
    ipAddress: '103.24.188.12',
    deviceId: 'MH-DIRECTORATE-TB-02',
    correlationId: 'corr-rep-exp-4491',
    stateId: 'state-mh',
    districtId: null,
    phcId: null,
    beforeState: null,
    afterState: {
      reportType: 'state_performance',
      format: 'pdf',
      downloadUrl: 's3://gov-portal-reports/exports/state-mh-perf-2026-09-16.pdf',
      fileSize: '4.2 MB',
    },
    aiRecPayload: null,
    metadata: { tier: 'State', parameters: { stateId: 'state-mh', period: 'last_30d' } },
  },
  {
    auditId: 'aud-20260916-008',
    action: 'redistribution.rejected',
    entityType: 'redistribution_recommendation',
    entityId: 'rec-thane-804',
    actorId: 'usr-dist-003',
    actorRole: 'district_admin',
    userName: 'Kavita Deshmukh (Thane)',
    userId: 'usr-dist-003',
    userRole: 'district_admin',
    createdAt: '2026-09-16T08:15:20.000Z',
    timestamp: '2026-09-16T08:15:20.000Z',
    sourceIp: '115.112.98.5',
    ipAddress: '115.112.98.5',
    deviceId: 'THANE-DHO-LAPTOP-01',
    correlationId: 'corr-redist-rej-3321',
    stateId: 'state-mh',
    districtId: 'dist-thane',
    phcId: 'phc-thane-01',
    beforeState: {
      recommendationId: 'rec-thane-804',
      quantity: 500,
      medicineName: 'Azithromycin 250mg',
      status: 'pending',
    },
    afterState: {
      recommendationId: 'rec-thane-804',
      status: 'rejected',
      rejectedReason: 'Source PHC cold chain malfunction reported; cannot guarantee potency',
    },
    aiRecPayload: {
      model: 'RedistributeNet-v2.1',
      calculatedSurplus: 600,
      distanceKm: 22.1,
    },
    metadata: { notes: 'Source PHC cold chain malfunction reported; cannot guarantee potency' },
  },
  {
    auditId: 'aud-20260916-009',
    action: 'shipment.rerouted',
    entityType: 'supply_chain_shipment',
    entityId: 'ship-2026-09-402',
    actorId: 'usr-state-001',
    actorRole: 'state_admin',
    userName: 'Smt. Priya Sharma (MH)',
    userId: 'usr-state-001',
    userRole: 'state_admin',
    createdAt: '2026-09-15T18:30:00.000Z',
    timestamp: '2026-09-15T18:30:00.000Z',
    sourceIp: '103.24.188.12',
    ipAddress: '103.24.188.12',
    deviceId: 'MH-DIRECTORATE-TB-02',
    correlationId: 'corr-ship-reroute-901',
    stateId: 'state-mh',
    districtId: 'dist-pune',
    phcId: null,
    beforeState: {
      shipmentId: 'ship-2026-09-402',
      destination: 'Pune Central Warehouse',
      carrier: 'SpeedLogistics India',
    },
    afterState: {
      shipmentId: 'ship-2026-09-402',
      destination: 'Nashik District Medical Store Depo',
      rerouteReason: 'Highway landslide diversion via NH-60 bypass',
    },
    aiRecPayload: {
      model: 'TransitRouteOptimizer-v1.4',
      avoidedDelayHours: 14.5,
      alternativeRouteRisk: 'low',
    },
    metadata: { reason: 'Highway landslide diversion via NH-60 bypass' },
  },
  {
    auditId: 'aud-20260916-010',
    action: 'role.permission_verified',
    entityType: 'security_session',
    entityId: 'sess-nat-00918',
    actorId: 'usr-nat-001',
    actorRole: 'national_admin',
    userName: 'Dr. Rajesh Kumar',
    userId: 'usr-nat-001',
    userRole: 'national_admin',
    createdAt: '2026-09-15T16:00:10.000Z',
    timestamp: '2026-09-15T16:00:10.000Z',
    sourceIp: '14.139.122.45',
    ipAddress: '14.139.122.45',
    deviceId: 'GOV-SEC-INSP-MAC-98A1',
    correlationId: 'corr-sec-token-8812',
    stateId: null,
    districtId: null,
    phcId: null,
    beforeState: null,
    afterState: {
      sessionValid: true,
      authMethod: 'NIC-SSO / PKI-Card',
      mfaVerified: true,
      roleAssigned: 'national_admin',
    },
    aiRecPayload: null,
    metadata: { authProvider: 'NIC e-Gov Auth Portal' },
  },
  {
    auditId: 'aud-20260916-011',
    action: 'user.created',
    entityType: 'user_account',
    entityId: 'usr-dist-004',
    actorId: 'usr-nat-001',
    actorRole: 'national_admin',
    userName: 'Dr. Rajesh Kumar',
    userId: 'usr-nat-001',
    userRole: 'national_admin',
    createdAt: '2026-09-15T14:15:00.000Z',
    timestamp: '2026-09-15T14:15:00.000Z',
    sourceIp: '14.139.122.45',
    ipAddress: '14.139.122.45',
    deviceId: 'GOV-SEC-INSP-MAC-98A1',
    correlationId: 'corr-user-create-902',
    stateId: 'state-ka',
    districtId: 'dist-bengaluru-urban',
    phcId: null,
    beforeState: null,
    afterState: {
      name: 'Dr. Ananya Rao',
      email: 'ananya.rao@karnataka.gov.in',
      role: 'district_admin',
      stateId: 'state-ka',
      districtId: 'dist-bengaluru-urban',
      status: 'active',
    },
    aiRecPayload: null,
    metadata: { designation: 'District Health Officer, Bengaluru Urban' },
  },
  {
    auditId: 'aud-20260916-012',
    action: 'threshold.updated',
    entityType: 'governance_config',
    entityId: 'cfg-thresholds-v3.3.9',
    actorId: 'usr-nat-001',
    actorRole: 'national_admin',
    userName: 'Dr. Rajesh Kumar',
    userId: 'usr-nat-001',
    userRole: 'national_admin',
    createdAt: '2026-09-15T11:20:00.000Z',
    timestamp: '2026-09-15T11:20:00.000Z',
    sourceIp: '14.139.122.45',
    ipAddress: '14.139.122.45',
    deviceId: 'GOV-SEC-INSP-MAC-98A1',
    correlationId: 'corr-cfg-9812400',
    stateId: null,
    districtId: null,
    phcId: null,
    beforeState: {
      oxygen_critical_threshold_days: 1.0,
      forecast_horizon_days: 14,
    },
    afterState: {
      oxygen_critical_threshold_days: 1.2,
      forecast_horizon_days: 14,
      change_justification: 'Early warning headroom expansion for peripheral high-altitude PHCs',
    },
    aiRecPayload: {
      model: 'OxygenLogisticsSimulator',
      predictedBottleneckReduction: '31%',
    },
    metadata: { reason: 'Early warning headroom expansion for peripheral high-altitude PHCs' },
  },
];
