import { RedistributionRecommendation } from '@/types';

export const MOCK_RECOMMENDATIONS: RedistributionRecommendation[] = [
  {
    recommendationId: 'REC-PUNE-001',
    medicineId: 'med-001',
    medicineName: 'Amoxicillin 500mg Tablets',
    fromPhcId: 'phc-kothrud',
    fromPhcName: 'Kothrud PHC',
    toPhcId: 'phc-hadapsar',
    toPhcName: 'Hadapsar PHC',
    districtId: 'dist-pune',
    quantity: 2500,
    unit: 'strips',
    urgency: 'critical',
    expectedBenefit: 'Averts zero-stock stockout for 340 patients/day; restores 16.5 days of safety stock.',
    distanceKm: 14.8,
    transitTimeMinutes: 32,
    sourceSurplus: 8400,
    destinationDeficit: 2500,
    reason: 'Hadapsar PHC reached 0 units today with a severe respiratory patient influx. Kothrud PHC holds 48 days of stock (buffer requirement: 14 days), leaving 5,900 strips safe reserve post-transfer.',
    aiConfidence: 0.96,
    status: 'pending',
    createdAt: new Date(Date.now() - 35 * 60_000).toISOString(),
  },
  {
    recommendationId: 'REC-PUNE-002',
    medicineId: 'med-003',
    medicineName: 'ORS Sachets 20.5g',
    fromPhcId: 'phc-baramati',
    fromPhcName: 'Baramati SDH',
    toPhcId: 'phc-wagholi',
    toPhcName: 'Wagholi PHC',
    districtId: 'dist-pune',
    quantity: 1800,
    unit: 'sachets',
    urgency: 'high',
    expectedBenefit: 'Supplies acute gastroenteritis surge; extends coverage from 1.5 to 18.0 days.',
    distanceKm: 28.4,
    transitTimeMinutes: 48,
    sourceSurplus: 11000,
    destinationDeficit: 1800,
    reason: 'Wagholi PHC reports acute diarrheal cluster (+3.2σ above baseline). Baramati SDH central store holds 11,000 sachets surplus above quarterly quota.',
    aiConfidence: 0.93,
    status: 'pending',
    createdAt: new Date(Date.now() - 58 * 60_000).toISOString(),
  },
  {
    recommendationId: 'REC-PUNE-003',
    medicineId: 'med-005',
    medicineName: 'Azithromycin 500mg Tablets',
    fromPhcId: 'phc-hadapsar',
    fromPhcName: 'Hadapsar PHC',
    toPhcId: 'phc-chakan',
    toPhcName: 'Chakan PHC',
    districtId: 'dist-pune',
    quantity: 800,
    unit: 'strips',
    urgency: 'high',
    expectedBenefit: 'Preempts projected stockout within 48h for industrial zone outpatient surge.',
    distanceKm: 34.2,
    transitTimeMinutes: 55,
    sourceSurplus: 3200,
    destinationDeficit: 800,
    reason: 'Chakan PHC footfall rose +185% over the past 7 days. Hadapsar PHC has ample central batch stock with 14 months to expiry.',
    aiConfidence: 0.91,
    status: 'pending',
    createdAt: new Date(Date.now() - 95 * 60_000).toISOString(),
  },
  {
    recommendationId: 'REC-PUNE-004',
    medicineId: 'med-004',
    medicineName: 'Metformin 500mg Tablets',
    fromPhcId: 'phc-kothrud',
    fromPhcName: 'Kothrud PHC',
    toPhcId: 'phc-velhe',
    toPhcName: 'Velhe PHC',
    districtId: 'dist-pune',
    quantity: 1200,
    unit: 'strips',
    urgency: 'medium',
    expectedBenefit: 'Ensures continuous NCD monthly dispensation for 210 registered diabetic patients.',
    distanceKm: 42.0,
    transitTimeMinutes: 70,
    sourceSurplus: 6500,
    destinationDeficit: 1200,
    reason: 'Velhe PHC road access is monsoon-sensitive. Pre-stocking NCD medicines mitigates rainy season delivery delays.',
    aiConfidence: 0.88,
    status: 'pending',
    createdAt: new Date(Date.now() - 140 * 60_000).toISOString(),
  },
  // Decided items with transfer lifecycle history
  {
    recommendationId: 'REC-PUNE-000-D1',
    medicineId: 'med-002',
    medicineName: 'Paracetamol 500mg Tablets',
    fromPhcId: 'phc-hadapsar',
    fromPhcName: 'Hadapsar PHC',
    toPhcId: 'phc-kothrud',
    toPhcName: 'Kothrud PHC',
    districtId: 'dist-pune',
    quantity: 3000,
    unit: 'strips',
    urgency: 'critical',
    expectedBenefit: 'Averted stockout during peak fever wave.',
    distanceKm: 14.8,
    transitTimeMinutes: 32,
    sourceSurplus: 9000,
    destinationDeficit: 3000,
    reason: 'Fever wave caused 3.8σ consumption spike. Approved by CMO.',
    aiConfidence: 0.95,
    status: 'approved',
    transferStatus: 'in_transit',
    createdAt: new Date(Date.now() - 5 * 3600_000).toISOString(),
    decisionAt: new Date(Date.now() - 4 * 3600_000).toISOString(),
    decisionBy: 'Dr. S. Patil (District Health Officer)',
    notes: 'Approved urgently due to viral fever outbreak in Kothrud ward.',
  },
  {
    recommendationId: 'REC-PUNE-000-D2',
    medicineId: 'med-006',
    medicineName: 'Ceftriaxone 1g Injection',
    fromPhcId: 'phc-baramati',
    fromPhcName: 'Baramati SDH',
    toPhcId: 'phc-chakan',
    toPhcName: 'Chakan PHC',
    districtId: 'dist-pune',
    quantity: 450,
    unit: 'vials',
    urgency: 'high',
    expectedBenefit: 'Reinforced inpatient emergency injectable reserves.',
    distanceKm: 58.0,
    transitTimeMinutes: 85,
    sourceSurplus: 1500,
    destinationDeficit: 450,
    reason: 'Severe infection cases referred from nearby industrial clusters.',
    aiConfidence: 0.92,
    status: 'modified',
    transferStatus: 'dispatched',
    createdAt: new Date(Date.now() - 8 * 3600_000).toISOString(),
    decisionAt: new Date(Date.now() - 6 * 3600_000).toISOString(),
    decisionBy: 'Dr. S. Patil (District Health Officer)',
    notes: 'Reduced quantity from 600 to 450 vials to maintain Baramati ICU buffer.',
  },
  {
    recommendationId: 'REC-PUNE-000-D3',
    medicineId: 'med-007',
    medicineName: 'Rabies Antiserum 1000 IU',
    fromPhcId: 'phc-chakan',
    fromPhcName: 'Chakan PHC',
    toPhcId: 'phc-baramati',
    toPhcName: 'Baramati SDH',
    districtId: 'dist-pune',
    quantity: 40,
    unit: 'vials',
    urgency: 'medium',
    expectedBenefit: 'Rebalance rare antiserum stock.',
    distanceKm: 58.0,
    transitTimeMinutes: 85,
    sourceSurplus: 80,
    destinationDeficit: 40,
    reason: 'Baramati reported stray animal bite cluster.',
    aiConfidence: 0.84,
    status: 'rejected',
    createdAt: new Date(Date.now() - 14 * 3600_000).toISOString(),
    decisionAt: new Date(Date.now() - 12 * 3600_000).toISOString(),
    decisionBy: 'Dr. S. Patil (District Health Officer)',
    notes: 'Rejected — State cold-chain depot already dispatched direct consignment of 100 vials.',
  },
  {
    recommendationId: 'REC-PUNE-000-D4',
    medicineId: 'med-008',
    medicineName: 'Insulin Regular 40 IU/ml',
    fromPhcId: 'phc-kothrud',
    fromPhcName: 'Kothrud PHC',
    toPhcId: 'phc-wagholi',
    toPhcName: 'Wagholi PHC',
    districtId: 'dist-pune',
    quantity: 120,
    unit: 'vials',
    urgency: 'high',
    expectedBenefit: 'Maintained uninterrupted cold chain insulin supply.',
    distanceKm: 22.1,
    transitTimeMinutes: 40,
    sourceSurplus: 350,
    destinationDeficit: 120,
    reason: 'Wagholi refrigerator temperature spike spoiled 60 vials.',
    aiConfidence: 0.94,
    status: 'completed',
    transferStatus: 'delivered',
    createdAt: new Date(Date.now() - 28 * 3600_000).toISOString(),
    decisionAt: new Date(Date.now() - 24 * 3600_000).toISOString(),
    decisionBy: 'Dr. S. Patil (District Health Officer)',
    notes: 'Approved and delivered with IoT digital temperature logger intact.',
  },
];

export async function fetchRedistributionRecommendations(districtId: string): Promise<RedistributionRecommendation[]> {
  try {
    const res = await fetch(`/api/v1/governance/redistribution/recommendations?district=${encodeURIComponent(districtId)}`, {
      credentials: 'include',
    });
    if (res.ok) {
      const data = await res.json();
      if (Array.isArray(data) && data.length > 0) {
        return data;
      }
    }
  } catch {
    // Fall back to pre-seeded mock dataset
  }
  return MOCK_RECOMMENDATIONS.filter((r) => !r.districtId || r.districtId === districtId || districtId === 'dist-pune');
}
