// ─────────────────────────────────────────────────────────────────────────────
// reportGenerator.ts — Client-side real file generation for Analytics exports
// Generates valid PDF (jsPDF), CSV, and XLSX (SheetJS) files that can be
// opened by standard desktop apps.
// ─────────────────────────────────────────────────────────────────────────────

import { ReportTier, ExportFormat, ReportTierConfig } from '@/lib/analyticsData';

export interface ReportParams {
  reportId: string;
  title: string;
  tier: ReportTier;
  format: ExportFormat;
  dateRange: string;
  scopeLabel: string;
  generatedBy: string;
  config: ReportTierConfig;
}

// ── Shared data rows used in CSV / XLSX ─────────────────────────────────────
function buildDataRows(params: ReportParams): (string | number)[][] {
  const header = ['Metric', 'Value', 'Delta / Notes'];
  const rows = params.config.keyMetrics.map((km) => [
    km.label,
    String(km.value),
    km.delta ?? '',
  ]);
  const sectionRows = params.config.sections.map((sec, i) => [
    `Section ${i + 1}`,
    sec,
    '',
  ]);
  return [header, ...rows, [], ['Statutory Sections', '', ''], ...sectionRows];
}

// ── PDF generation via jsPDF ─────────────────────────────────────────────────
export async function generatePDF(params: ReportParams): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  let y = 22;

  doc.setFillColor(30, 64, 175);
  doc.rect(0, 0, pageW, 14, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('SMART HEALTH & SUPPLY CHAIN RESILIENCE — GOVERNANCE PORTAL', margin, 9.5);

  y = 26;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(params.title, margin, y);
  y += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Tier: ${params.tier.toUpperCase()}  |  Period: ${params.dateRange.toUpperCase()}  |  Scope: ${params.scopeLabel}`,
    margin, y
  );
  y += 5;
  doc.text(`Generated by: ${params.generatedBy}  |  Report ID: ${params.reportId}  |  Date: ${new Date().toLocaleString()}`, margin, y);
  y += 6;

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(71, 85, 105);
  const subtitleLines = doc.splitTextToSize(params.config.subtitle, pageW - margin * 2);
  doc.text(subtitleLines, margin, y);
  y += subtitleLines.length * 5 + 6;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('KEY PERFORMANCE METRICS', margin, y);
  y += 7;

  params.config.keyMetrics.forEach((km, i) => {
    const rowY = y + i * 12;
    if (i % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, rowY - 4, pageW - margin * 2, 11, 'F');
    }
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(km.label, margin + 3, rowY + 3);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(37, 99, 235);
    doc.text(String(km.value), margin + 90, rowY + 3);
    if (km.delta) {
      doc.setTextColor(100, 116, 139);
      doc.text(km.delta, margin + 140, rowY + 3);
    }
  });

  y += params.config.keyMetrics.length * 12 + 8;

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('STATUTORY ANALYSIS SECTIONS', margin, y);
  y += 7;

  params.config.sections.forEach((sec, i) => {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    const lines = doc.splitTextToSize(`${i + 1}. ${sec}`, pageW - margin * 2 - 4);
    doc.text(lines, margin + 3, y);
    y += lines.length * 5 + 2;
  });

  y += 4;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageW - margin, y);
  y += 5;
  doc.setFontSize(7.5);
  doc.setTextColor(148, 163, 184);
  doc.text('This document is auto-generated by the AURA Vantage Governance Portal. For official use only.', margin, y);

  return doc.output('blob');
}

// ── CSV generation ───────────────────────────────────────────────────────────
export function generateCSV(params: ReportParams): Blob {
  const rows = buildDataRows(params);
  const meta = [
    ['Smart Health & Supply Chain Resilience - Governance Report'],
    ['Report Title', params.title],
    ['Report ID', params.reportId],
    ['Tier', params.tier.toUpperCase()],
    ['Period', params.dateRange.toUpperCase()],
    ['Scope', params.scopeLabel],
    ['Generated By', params.generatedBy],
    ['Generated At', new Date().toISOString()],
    [],
  ];
  const allRows = [...meta, ...rows];
  const csv = allRows
    .map((row) =>
      row
        .map((cell) => {
          const str = String(cell ?? '');
          if (str.includes(',') || str.includes('"') || str.includes('\n')) {
            return `"${str.replace(/"/g, '""')}"`;
          }
          return str;
        })
        .join(',')
    )
    .join('\r\n');
  return new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
}

// ── XLSX generation via SheetJS ──────────────────────────────────────────────
export async function generateXLSX(params: ReportParams): Promise<Blob> {
  const XLSX = await import('xlsx');
  const ws_data: (string | number)[][] = [
    ['Smart Health & Supply Chain Resilience - Governance Report'],
    [],
    ['Report Title', params.title],
    ['Report ID', params.reportId],
    ['Tier', params.tier.toUpperCase()],
    ['Period', params.dateRange.toUpperCase()],
    ['Scope', params.scopeLabel],
    ['Generated By', params.generatedBy],
    ['Generated At', new Date().toLocaleString()],
    [],
    ['KEY METRICS'],
    ['Metric', 'Value', 'Delta / Notes'],
    ...params.config.keyMetrics.map((km) => [km.label, String(km.value), km.delta ?? '']),
    [],
    ['STATUTORY ANALYSIS SECTIONS'],
    ['#', 'Section Description'],
    ...params.config.sections.map((sec, i) => [i + 1, sec]),
  ];
  const ws = XLSX.utils.aoa_to_sheet(ws_data);
  ws['!cols'] = [{ wch: 35 }, { wch: 30 }, { wch: 30 }];
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, `${params.tier.toUpperCase()} Report`);
  const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Blob([wbout], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
}

// ── Master dispatcher ────────────────────────────────────────────────────────
export async function generateReport(params: ReportParams): Promise<string> {
  let blob: Blob;
  switch (params.format) {
    case 'PDF':
      blob = await generatePDF(params);
      break;
    case 'CSV':
      blob = generateCSV(params);
      break;
    case 'XLSX':
      blob = await generateXLSX(params);
      break;
    default:
      throw new Error(`Unknown format: ${params.format}`);
  }
  return URL.createObjectURL(blob);
}
