// -----------------------------------------------------------------------------
// Legal Content — Terms & Conditions and Privacy Policy
// AURA Health Platform (Build with AI: Code for Communities — Second Edition)
// -----------------------------------------------------------------------------

export interface LegalSection {
  title: string;
  paragraphs: string[];
}

export const TERMS_AND_CONDITIONS: {
  title: string;
  lastUpdated: string;
  version: string;
  sections: LegalSection[];
} = {
  title: 'Terms & Conditions',
  lastUpdated: 'September 2026',
  version: '2.1.0',
  sections: [
    {
      title: '1. Acceptance of Terms & Governance Framework',
      paragraphs: [
        'By accessing, deploying, or utilizing the Autonomous Universal Resilience Architecture (AURA) Health Platform, you agree to be bound by these Terms and Conditions and all applicable municipal, state, national, and international healthcare compliance standards.',
        'This software was architected and developed by Ansh, Arya, Sumiya, and Abdullah for the "Build with AI: Code for Communities — Second Edition" hackathon initiative to provide high-assurance healthcare supply chain resilience, automated stockout mitigation, and decentralized federated health intelligence.'
      ]
    },
    {
      title: '2. Authorized Roles & Operational Jurisdictions',
      paragraphs: [
        'Access to administrative, dispatch, and redistribution command layers is restricted to authorized personnel including Primary Health Centre (PHC) Medical Officers, District Magistrates, State Health Directors, and Ministry Health Governance officials.',
        'Users are granted role-based access control (RBAC) strictly constrained by geographic and institutional jurisdictions. Unauthorized attempts to alter ledger balances, override emergency dispatches, or spoof biometric or device telemetry will result in immediate credential revocation and automated audit logging.'
      ]
    },
    {
      title: '3. Clinical & Operational Decision Support Advisory',
      paragraphs: [
        'AURA utilizes predictive artificial intelligence, epidemiological outbreak modeling, and automated inventory redistribution heuristics (FEFO / First-Expired, First-Out).',
        'While AURA provides algorithmic recommendations, early warnings, and logistics automation, final clinical and administrative accountability remains with certified medical practitioners and appointed administrative authorities. AURA is an operational decision support system and should be audited alongside local clinical protocols.'
      ]
    },
    {
      title: '4. Autonomous Redistribution & Inventory Protocols',
      paragraphs: [
        'Automated redistribution proposals generated by the platform compute multi-variable logistics costs, transit times, consumption velocities, and critical reserve thresholds across inter-PHC and district buffers.',
        'Accepted redistribution orders constitute binding logistics dispatches. In emergency trigger conditions (Code Red / Outbreak protocols), algorithmic dispatches adhere to predefined civil contingency guidelines.'
      ]
    },
    {
      title: '5. Intellectual Property & Community Licensing',
      paragraphs: [
        'AURA is produced under open governance principles for community healthcare empowerment. All intellectual property developed by the team (Ansh, Arya, Sumiya, Abdullah) for the "Build with AI: Code for Communities — Second Edition" is licensed to foster public health resilience, academic research, and non-profit humanitarian deployments.',
        'Commercial distribution without explicit endorsement from the core development consortium is strictly prohibited.'
      ]
    },
    {
      title: '6. Limitation of Liability',
      paragraphs: [
        'In no event shall the authors, maintainers, or development partners be liable for damages resulting from local telecommunication outages, uncalibrated third-party hardware sensors, or willful disruption of synchronization pipelines beyond the autonomous recovery bounds guaranteed by the platform architecture.'
      ]
    }
  ]
};

export const PRIVACY_POLICY: {
  title: string;
  lastUpdated: string;
  version: string;
  sections: LegalSection[];
} = {
  title: 'Privacy Policy',
  lastUpdated: 'September 2026',
  version: '2.1.0',
  sections: [
    {
      title: '1. Privacy-by-Design & Data Sovereignty Principles',
      paragraphs: [
        'The AURA Health Platform was engineered from the ground up by Ansh, Arya, Sumiya, and Abdullah with a strict Privacy-by-Design mandate under the "Build with AI: Code for Communities — Second Edition" charter.',
        'All patient-identifiable data remains strictly within sovereign boundary borders and local facility databases. Raw electronic health records never leave the originating Primary Health Centre (PHC) without cryptographically verified patient consent and de-identification.'
      ]
    },
    {
      title: '2. Differential Privacy Guarantees (ε ≤ 5.0)',
      paragraphs: [
        'Cross-district and cross-border epidemiology telemetry (such as the BRICS Sovereign Health Intelligence network) employs mathematically rigorous Differential Privacy mechanisms with an overall privacy budget of ε ≤ 5.0 and Gaussian perturbation noise.',
        'This mathematical guarantee guarantees that no individual patient or unique diagnosis can be reverse-engineered or reconstructed from federated model weights, aggregated outbreak clusters, or global training rounds.'
      ]
    },
    {
      title: '3. Compliance with Healthcare Regulations',
      paragraphs: [
        'AURA aligns with the Ayushman Bharat Digital Mission (ABDM) standards, the Digital Information Security in Healthcare Act (DISHA), the Health Insurance Portability and Accountability Act (HIPAA), and GDPR guidelines for biometric and biomedical telemetry.',
        'Patient records, prescriptions processed through optical neural character recognition, and triage categorizations are sanitized immediately in client memory and hashed before indexing.'
      ]
    },
    {
      title: '4. Local Storage & Edge Offline Data Synchronization',
      paragraphs: [
        'To support low-connectivity remote clinics, AURA Point PHC uses encrypted client-side IndexedDB databases (Dexie.js). All synchronized mutation logs are signed with cryptographic device keys and validated against PostgreSQL row-level security (RLS) policies upon WAN restoration.',
        'Local browser sessions do not store tracking cookies or third-party behavioral analytics scripts.'
      ]
    },
    {
      title: '5. Audit Trails & Cryptographic Accountability',
      paragraphs: [
        'Every query submitted to the Interactive Intelligence Agent (Copilot), every inventory adjustment, and every dispatch override generates an immutable tamper-evident audit record containing user IDs, timestamps, and hash digests.',
        'These audit trails are accessible exclusively to verified compliance officers and jurisdiction administrators.'
      ]
    },
    {
      title: '6. Contact & Data Protection Inquiries',
      paragraphs: [
        'For queries concerning privacy compliance, data protection impact assessments (DPIAs), or technical audit inquiries, please contact the development team (Ansh, Arya, Sumiya, Abdullah) via the official AURA Health Platform community repository or governance administrative desk.'
      ]
    }
  ]
};
