import os

lines = []
def L(s): lines.append(s)

L("import { PoolClient } from 'pg';")
L("import { pool, withTenantContext, TenantClaims } from '../../db/pool';")
L("import { eventBus } from '../../events/eventBus';")
L("import { InventoryService } from '../inventory/inventoryService';")
L("")
L("export interface BillingItem {")
L("  medicine_id: string;")
L("  quantity: number;")
L("  unit_price?: number;")
L("}")
L("")
L("export interface CheckoutInput {")
L("  client_txn_id: string;")
L("  patient_ref?: string;")
L("  dispensed_by_staff_id?: string;")
L("  items: BillingItem[];")
L("  client_timestamp?: string;")
L("}")
L("")
L("export interface DispensedItemResult {")
L("  batch_id: string;")
L("  medicine_id: string;")
L("  quantity_deducted: number;")
L("  unit_price: number;")
L("}")
L("")
L("export interface CheckoutSuccess {")
L("  outcome: 'success';")
L("  transaction_id: string;")
L("  client_txn_id: string;")
L("  already_existed: boolean;")
L("  total_amount: number;")
L("  dispensed_items: DispensedItemResult[];")
L("}")
L("")
L("export interface StockShortfall {")
L("  medicine_id: string;")
L("  requested_qty: number;")
L("  available_qty: number;")
L("}")
L("")
L("export interface CheckoutInsufficientStock {")
L("  outcome: 'insufficient_stock';")
L("  shortfalls: StockShortfall[];")
L("}")
L("")
L("export type CheckoutResult = CheckoutSuccess | CheckoutInsufficientStock;")
L("")
L("export class BillingService {")
L("  /**")
L("   * Canonical FEFO checkout. Both REST (checkoutRest) and sync engine delegate here.")
L("   * Architecture SS3.3.1, SS5.1: single implementation, no drift.")
L("   *")
L("   * Steps:")
L("   *  1. Idempotency guard on client_txn_id")
L("   *  2. SELECT ... FOR UPDATE SKIP LOCKED ordered expiry_date ASC per item")
L("   *  3. Return CheckoutInsufficientStock if any item under-stocked")
L("   *  4. INSERT billing_transactions, deduct batches in FEFO order,")
L("   *     INSERT dispensed_items + consumption_velocity per batch slice")
L("   *  5. Recompute threshold status per medicine, emit events")
L("   */")
L("  static async checkout(")
L("    client: PoolClient,")
L("    phcId: string,")
L("    input: CheckoutInput,")
L("  ): Promise<CheckoutResult> {")
L("    const { client_txn_id, patient_ref, dispensed_by_staff_id, items, client_timestamp } = input;")
L("    const txnTs = client_timestamp ?? new Date().toISOString();")
L("")
L("    // 1. Idempotency guard")
L("    const existingRes = await client.query<{ id: string; total_amount: number }>(")
L("      `SELECT id, total_amount FROM billing_transactions")
L("       WHERE phc_id = $1 AND client_txn_id = $2`,")
L("      [phcId, client_txn_id],")
L("    );")
L("    if (existingRes.rows.length > 0) {")
L("      const existing = existingRes.rows[0];")
L("      const diRes = await client.query<DispensedItemResult>(")
L("        `SELECT batch_id, medicine_id, quantity AS quantity_deducted, unit_price")
L("         FROM dispensed_items WHERE billing_transaction_id = $1`,")
L("        [existing.id],")
L("      );")
L("      return {")
L("        outcome: 'success',")
L("        transaction_id: existing.id,")
L("        client_txn_id,")
L("        already_existed: true,")
L("        total_amount: Number(existing.total_amount),")
L("        dispensed_items: diRes.rows,")
L("      };")
L("    }")
L("")
L("    // 2. FEFO lock + availability scan (SKIP LOCKED prevents deadlocks on concurrent checkouts)")
L("    interface BatchRow { id: string; remaining_qty: number; expiry_date: string; minimum_threshold: number; }")
L("    const batchCache = new Map<string, BatchRow[]>();")
L("    const shortfalls: StockShortfall[] = [];")
L("")
L("    for (const item of items) {")
L("      const batchRes = await client.query<BatchRow>(")
L("        `SELECT id, remaining_qty, expiry_date, minimum_threshold")
L("         FROM inventory_batches")
L("         WHERE phc_id = $1")
L("           AND medicine_id = $2")
L("           AND remaining_qty > 0")
L("           AND (expiry_date IS NULL OR expiry_date > CURRENT_DATE)")
L("         ORDER BY expiry_date ASC")
L("         FOR UPDATE SKIP LOCKED`,")
L("        [phcId, item.medicine_id],")
L("      );")
L("      const available = batchRes.rows.reduce((acc, r) => acc + Number(r.remaining_qty), 0);")
L("      batchCache.set(item.medicine_id, batchRes.rows);")
L("      if (available < item.quantity) {")
L("        shortfalls.push({ medicine_id: item.medicine_id, requested_qty: item.quantity, available_qty: available });")
L("      }")
L("    }")
L("")
L("    // 3. Return insufficient stock (caller maps to HTTP 409 or sync conflict shape)")
L("    if (shortfalls.length > 0) {")
L("      return { outcome: 'insufficient_stock', shortfalls };")
L("    }")
L("")
L("    // 4. Persist billing_transactions header")
L("    const totalAmount = items.reduce((sum, i) => sum + i.quantity * (i.unit_price ?? 0), 0);")
L("    const txnRes = await client.query<{ id: string }>(")
L("      `INSERT INTO billing_transactions (")
L("         phc_id, client_txn_id, patient_ref, dispensed_by_staff_id,")
L("         total_amount, client_timestamp, status")
L("       ) VALUES ($1, $2, $3, $4, $5, $6, 'completed')")
L("       RETURNING id`,")
L("      [phcId, client_txn_id, patient_ref ?? null, dispensed_by_staff_id ?? null, totalAmount, txnTs],")
L("    );")
L("    const transactionId = txnRes.rows[0].id;")
L("    const dispensedItems: DispensedItemResult[] = [];")
L("")
L("    // 5. FEFO deduction across batches")
L("    for (const item of items) {")
L("      const batches = batchCache.get(item.medicine_id) ?? [];")
L("      let needed = item.quantity;")
L("      const unitPrice = item.unit_price ?? 0;")
L("      for (const batch of batches) {")
L("        if (needed <= 0) break;")
L("        const deduct = Math.min(needed, Number(batch.remaining_qty));")
L("        await client.query(")
L("          `UPDATE inventory_batches SET remaining_qty = remaining_qty - $1 WHERE id = $2`,")
L("          [deduct, batch.id],")
L("        );")
L("        await client.query(")
L("          `INSERT INTO dispensed_items (billing_transaction_id, batch_id, medicine_id, quantity, unit_price)")
L("           VALUES ($1, $2, $3, $4, $5)`,")
L("          [transactionId, batch.id, item.medicine_id, deduct, unitPrice],")
L("        );")
L("        await client.query(")
L("          `INSERT INTO consumption_velocity (time, phc_id, medicine_id, qty_dispensed)")
L("           VALUES ($1, $2, $3, $4)`,")
L("          [txnTs, phcId, item.medicine_id, deduct],")
L("        );")
L("        dispensedItems.push({ batch_id: batch.id, medicine_id: item.medicine_id, quantity_deducted: deduct, unit_price: unitPrice });")
L("        needed -= deduct;")
L("      }")
L("    }")
L("")
L("    // 6. Recompute threshold status per medicine after deduction")
L("    const dispensedMedIds = [...new Set(items.map((i) => i.medicine_id))];")
L("    for (const medId of dispensedMedIds) {")
L("      const freshBatches = await client.query<{ remaining_qty: number; expiry_date: string; minimum_threshold: number }>(")
L("        `SELECT remaining_qty, expiry_date, minimum_threshold FROM inventory_batches")
L("         WHERE phc_id = $1 AND medicine_id = $2`,")
L("        [phcId, medId],")
L("      );")
L("      const healthStatus = InventoryService.deriveStockStatus(freshBatches.rows);")
L("      if (healthStatus === 'CRITICAL' || healthStatus === 'EXPIRED') {")
L("        setImmediate(() => {")
L("          eventBus.publish('stock.threshold_breached', { phc_id: phcId, medicine_id: medId, health_status: healthStatus, triggered_by: 'billing_checkout' }, 'billing-service').catch(() => {});")
L("        });")
L("      }")
L("    }")
L("")
L("    // 7. Emit billing.transaction_completed (fire-and-forget, safe after commit)")
L("    setImmediate(() => {")
L("      eventBus.publish(")
L("        'billing.transaction_completed',")
L("        { transaction_id: transactionId, phc_id: phcId, client_txn_id, patient_ref: patient_ref ?? null, total_amount: totalAmount, item_count: dispensedItems.length, dispensed_medicine_ids: dispensedMedIds },")
L("        'billing-service',")
L("      ).catch(() => {});")
L("    });")
L("")
L("    return { outcome: 'success', transaction_id: transactionId, client_txn_id, already_existed: false, total_amount: totalAmount, dispensed_items: dispensedItems };")
L("  }")
L("")
L("  /** REST wrapper: manages its own BEGIN/COMMIT around checkout(). */")
L("  static async checkoutRest(phcId: string, input: CheckoutInput): Promise<CheckoutResult> {")
L("    const client = await pool.connect();")
L("    try {")
L("      await client.query('BEGIN');")
L("      await client.query(`SELECT set_config('app.current_phc_id', $1, true)`, [phcId]);")
L("      const result = await BillingService.checkout(client, phcId, input);")
L("      if (result.outcome === 'success') {")
L("        await client.query('COMMIT');")
L("      } else {")
L("        await client.query('ROLLBACK');")
L("      }")
L("      return result;")
L("    } catch (err) {")
L("      await client.query('ROLLBACK');")
L("      throw err;")
L("    } finally {")
L("      client.release();")
L("    }")
L("  }")
L("")
L("  /** List billing history for a PHC (most-recent first, capped at 500). */")
L("  static async listTransactions(phcId: string, claims: TenantClaims): Promise<{ transactions: any[] }> {")
L("    return withTenantContext(claims, async (client) => {")
L("      const res = await client.query(")
L("        `SELECT id, client_txn_id, patient_ref, dispensed_by_staff_id,")
L("                total_amount, client_timestamp, server_timestamp, status")
L("         FROM billing_transactions")
L("         WHERE phc_id = $1")
L("         ORDER BY server_timestamp DESC LIMIT 500`,")
L("        [phcId],")
L("      );")
L("      return { transactions: res.rows };")
L("    });")
L("  }")
L("")
L("  /** Full detail for one transaction (header + dispensed_items). */")
L("  static async getTransactionDetails(phcId: string, transactionId: string, claims: TenantClaims): Promise<any> {")
L("    return withTenantContext(claims, async (client) => {")
L("      const txnRes = await client.query(")
L("        `SELECT id, client_txn_id, patient_ref, dispensed_by_staff_id,")
L("                total_amount, client_timestamp, server_timestamp, status")
L("         FROM billing_transactions WHERE id = $1 AND phc_id = $2`,")
L("        [transactionId, phcId],")
L("      );")
L("      if (txnRes.rows.length === 0) {")
L("        const err: any = new Error('TRANSACTION_NOT_FOUND');")
L("        err.statusCode = 404;")
L("        throw err;")
L("      }")
L("      const diRes = await client.query(")
L("        `SELECT di.id, di.batch_id, di.medicine_id, m.name AS medicine_name,")
L("                di.quantity, di.unit_price")
L("         FROM dispensed_items di")
L("         JOIN medicines m ON m.id = di.medicine_id")
L("         WHERE di.billing_transaction_id = $1`,")
L("        [transactionId],")
L("      );")
L("      return { transaction: txnRes.rows[0], dispensed_items: diRes.rows };")
L("    });")
L("  }")
L("}")

out = '\n'.join(lines)
with open('src/modules/billing/billingService.ts', 'w', encoding='utf-8') as f:
    f.write(out)
print('OK len=' + str(len(out)))
