lines = []
def L(s): lines.append(s)

L("/**")
L(" * test_billing_fefo.ts -- Integration tests for Prompt 9: FEFO Billing / Dispensing Engine")
L(" *")
L(" * Scenarios:")
L(" *  1. Happy-path checkout: single medicine, single batch, FEFO order honoured")
L(" *  2. Cross-batch deduction: qty spans two batches, earliest-expiry drained first")
L(" *  3. Idempotency: same client_txn_id returns already_existed:true, no duplicate writes")
L(" *  4. Insufficient stock: returns CheckoutInsufficientStock with shortfalls array")
L(" *  5. Sync path maps insufficient_stock -> stock_oversold conflict (SS8.3)")
L(" *  6. billing.transaction_completed event emitted after successful checkout")
L(" *  7. stock.threshold_breached emitted when stock goes CRITICAL after dispensing")
L(" */")
L("")
L("import { PoolClient } from 'pg';")
L("import { eventBus } from '../src/events/eventBus';")
L("")
L("// --------------- In-memory DB state ---------------")
L("interface Batch { id: string; phc_id: string; medicine_id: string; remaining_qty: number; expiry_date: string; minimum_threshold: number; }")
L("interface BillingTxn { id: string; phc_id: string; client_txn_id: string; patient_ref: string|null; dispensed_by_staff_id: string|null; total_amount: number; client_timestamp: string; status: string; }")
L("interface DispensedItem { id: string; billing_transaction_id: string; batch_id: string; medicine_id: string; quantity: number; unit_price: number; }")
L("interface ConsumptionRow { medicine_id: string; qty_dispensed: number; }")
L("")
L("let batches: Batch[] = [];")
L("let billingTxns: BillingTxn[] = [];")
L("let dispensedItems: DispensedItem[] = [];")
L("let consumptionRows: ConsumptionRow[] = [];")
L("let nextId = 1;")
L("function uid() { return String(nextId++); }")
L("")
L("function resetState() {")
L("  batches = []; billingTxns = []; dispensedItems = []; consumptionRows = []; nextId = 1;")
L("  eventBus.clearHistory();")
L("}")
L("")
L("// --------------- Mock PoolClient ---------------")
L("type QueryFn = (sql: string, params?: any[]) => Promise<{ rows: Record<string,any>[] }>;")
L("")
L("function makeMockClient(): PoolClient {")
L("  const handler: QueryFn = async (sql: string, params: any[] = []) => {")
L("    const s = sql.replace(/\\s+/g, ' ').trim();")
L("")
L("    // Idempotency SELECT on billing_transactions by client_txn_id")
L("    if (s.includes('FROM billing_transactions') && s.includes('client_txn_id')) {")
L("      const found = billingTxns.find((t) => t.phc_id === params[0] && t.client_txn_id === params[1]);")
L("      return { rows: found ? [{ id: found.id, total_amount: found.total_amount }] : [] };")
L("    }")
L("    // Re-fetch dispensed_items for idempotency reply")
L("    if (s.includes('FROM dispensed_items') && s.includes('billing_transaction_id')) {")
L("      const rows = dispensedItems.filter((d) => d.billing_transaction_id === params[0]).map((d) => ({")
L("        batch_id: d.batch_id, medicine_id: d.medicine_id, quantity_deducted: d.quantity, unit_price: d.unit_price,")
L("      }));")
L("      return { rows };")
L("    }")
L("    // FEFO batch lock SELECT")
L("    if (s.includes('FOR UPDATE SKIP LOCKED')) {")
L("      const eligible = batches")
L("        .filter((b) => b.phc_id === params[0] && b.medicine_id === params[1] && b.remaining_qty > 0)")
L("        .sort((a, b2) => a.expiry_date.localeCompare(b2.expiry_date));")
L("      return { rows: eligible.map((b) => ({ id: b.id, remaining_qty: b.remaining_qty, expiry_date: b.expiry_date, minimum_threshold: b.minimum_threshold })) };")
L("    }")
L("    // INSERT billing_transactions")
L("    if (s.includes('INSERT INTO billing_transactions')) {")
L("      const id = uid();")
L("      billingTxns.push({ id, phc_id: params[0], client_txn_id: params[1], patient_ref: params[2], dispensed_by_staff_id: params[3], total_amount: params[4], client_timestamp: params[5], status: 'completed' });")
L("      return { rows: [{ id }] };")
L("    }")
L("    // UPDATE inventory_batches")
L("    if (s.includes('UPDATE inventory_batches')) {")
L("      const batch = batches.find((b) => b.id === params[1]);")
L("      if (batch) batch.remaining_qty -= params[0];")
L("      return { rows: [] };")
L("    }")
L("    // INSERT dispensed_items")
L("    if (s.includes('INSERT INTO dispensed_items')) {")
L("      dispensedItems.push({ id: uid(), billing_transaction_id: params[0], batch_id: params[1], medicine_id: params[2], quantity: params[3], unit_price: params[4] });")
L("      return { rows: [] };")
L("    }")
L("    // INSERT consumption_velocity")
L("    if (s.includes('INSERT INTO consumption_velocity')) {")
L("      consumptionRows.push({ medicine_id: params[2], qty_dispensed: params[3] });")
L("      return { rows: [] };")
L("    }")
L("    // Threshold re-check SELECT (all batches for a medicine)")
L("    if (s.includes('FROM inventory_batches') && s.includes('medicine_id = $2')) {")
L("      return { rows: batches.filter((b) => b.phc_id === params[0] && b.medicine_id === params[1]) };")
L("    }")
L("    if (s.includes('set_config') || /^(BEGIN|COMMIT|ROLLBACK)$/.test(s)) return { rows: [] };")
L("    return { rows: [] };")
L("  };")
L("  return { query: handler, release: () => {} } as unknown as PoolClient;")
L("}")
L("")
L("// --------------- Test helpers ---------------")
L("let passed = 0;")
L("let failed = 0;")
L("")
L("async function test(name: string, fn: () => Promise<void>) {")
L("  try {")
L("    await fn();")
L("    console.log(`  \u2713 ${name}`);")
L("    passed++;")
L("  } catch (err: any) {")
L("    console.error(`  \u2717 ${name}`);")
L("    console.error(`      ${err.message}`);")
L("    failed++;")
L("  }")
L("}")
L("")
L("function assert(cond: boolean, msg: string) {")
L("  if (!cond) throw new Error(msg);")
L("}")
L("")
L("async function getBillingService() {")
L("  return (await import('../src/modules/billing/billingService')).BillingService;")
L("}")
L("")
L("// =================== SCENARIOS ===================")
L("")
L("async function scenario1() {")
L("  console.log('\\nScenario 1: Happy-path checkout (single medicine, single batch)');")
L("  resetState();")
L("  const BS = await getBillingService();")
L("  const phcId = 'phc-1'; const medId = 'med-para';")
L("  batches.push({ id: 'batch-A', phc_id: phcId, medicine_id: medId, remaining_qty: 100, expiry_date: '2027-06-01', minimum_threshold: 20 });")
L("  const client = makeMockClient();")
L("")
L("  await test('returns outcome: success', async () => {")
L("    const r = await BS.checkout(client, phcId, { client_txn_id: 'txn-001', items: [{ medicine_id: medId, quantity: 30, unit_price: 5 }] });")
L("    assert(r.outcome === 'success', `Expected success, got ${r.outcome}`);")
L("  });")
L("  await test('deducts correct qty from batch (100 - 30 = 70)', async () => {")
L("    assert(batches[0].remaining_qty === 70, `Expected 70, got ${batches[0].remaining_qty}`);")
L("  });")
L("  await test('inserts billing_transactions row', async () => {")
L("    assert(billingTxns.length === 1, `Expected 1 txn`);")
L("    assert(billingTxns[0].client_txn_id === 'txn-001', 'Wrong client_txn_id');")
L("  });")
L("  await test('inserts dispensed_item with quantity 30', async () => {")
L("    assert(dispensedItems.length === 1 && dispensedItems[0].quantity === 30, `Unexpected dispensed qty`);")
L("  });")
L("  await test('inserts consumption_velocity row', async () => {")
L("    assert(consumptionRows.length === 1 && consumptionRows[0].qty_dispensed === 30, 'Velocity row missing');")
L("  });")
L("}")
L("")
L("async function scenario2() {")
L("  console.log('\\nScenario 2: Cross-batch FEFO deduction (earliest-expiry first)');")
L("  resetState();")
L("  const BS = await getBillingService();")
L("  const phcId = 'phc-1'; const medId = 'med-amox';")
L("  batches.push({ id: 'batch-old', phc_id: phcId, medicine_id: medId, remaining_qty: 20, expiry_date: '2026-12-01', minimum_threshold: 10 });")
L("  batches.push({ id: 'batch-new', phc_id: phcId, medicine_id: medId, remaining_qty: 50, expiry_date: '2027-06-01', minimum_threshold: 10 });")
L("  const client = makeMockClient();")
L("")
L("  await BS.checkout(client, phcId, { client_txn_id: 'txn-002', items: [{ medicine_id: medId, quantity: 30 }] });")
L("")
L("  await test('checkout success spanning two batches', async () => {")
L("    assert(billingTxns.length === 1, 'Expected 1 txn');")
L("  });")
L("  await test('older batch (2026-12-01) fully drained first', async () => {")
L("    assert(batches[0].remaining_qty === 0, `Expected 0, got ${batches[0].remaining_qty}`);")
L("  });")
L("  await test('newer batch partially consumed (50 - 10 = 40)', async () => {")
L("    assert(batches[1].remaining_qty === 40, `Expected 40, got ${batches[1].remaining_qty}`);")
L("  });")
L("  await test('two dispensed_item rows (one per batch)', async () => {")
L("    assert(dispensedItems.length === 2, `Expected 2, got ${dispensedItems.length}`);")
L("  });")
L("}")
L("")
L("async function scenario3() {")
L("  console.log('\\nScenario 3: Idempotency -- duplicate client_txn_id');")
L("  resetState();")
L("  const BS = await getBillingService();")
L("  const phcId = 'phc-1'; const medId = 'med-p';")
L("  batches.push({ id: 'batch-Z', phc_id: phcId, medicine_id: medId, remaining_qty: 100, expiry_date: '2027-01-01', minimum_threshold: 5 });")
L("  const client = makeMockClient();")
L("")
L("  await BS.checkout(client, phcId, { client_txn_id: 'txn-idem', items: [{ medicine_id: medId, quantity: 10, unit_price: 2 }] });")
L("  const qtyAfter1 = batches[0].remaining_qty;")
L("  const dispAfter1 = dispensedItems.length;")
L("")
L("  await test('second call returns already_existed: true', async () => {")
L("    const r = await BS.checkout(client, phcId, { client_txn_id: 'txn-idem', items: [{ medicine_id: medId, quantity: 10, unit_price: 2 }] }) as any;")
L("    assert(r.outcome === 'success', 'expected success');")
L("    assert(r.already_existed === true, 'expected already_existed=true');")
L("  });")
L("  await test('no additional stock deducted on replay', async () => {")
L("    assert(batches[0].remaining_qty === qtyAfter1, `Qty changed after replay`);")
L("  });")
L("  await test('no extra dispensed_item row on replay', async () => {")
L("    assert(dispensedItems.length === dispAfter1, `Got extra dispensed rows`);")
L("  });")
L("}")
L("")
L("async function scenario4() {")
L("  console.log('\\nScenario 4: Insufficient stock');")
L("  resetState();")
L("  const BS = await getBillingService();")
L("  const phcId = 'phc-1'; const medId = 'med-rare';")
L("  batches.push({ id: 'batch-tiny', phc_id: phcId, medicine_id: medId, remaining_qty: 5, expiry_date: '2027-01-01', minimum_threshold: 2 });")
L("  const client = makeMockClient();")
L("")
L("  await test('returns outcome: insufficient_stock', async () => {")
L("    const r = await BS.checkout(client, phcId, { client_txn_id: 'txn-bad', items: [{ medicine_id: medId, quantity: 50 }] });")
L("    assert(r.outcome === 'insufficient_stock', `Got ${r.outcome}`);")
L("  });")
L("  await test('shortfalls array contains correct medicine and available_qty', async () => {")
L("    const r = await BS.checkout(client, phcId, { client_txn_id: 'txn-bad2', items: [{ medicine_id: medId, quantity: 50 }] }) as any;")
L("    assert(r.shortfalls.length === 1, 'Expected 1 shortfall');")
L("    assert(r.shortfalls[0].medicine_id === medId, 'Wrong medicine_id');")
L("    assert(r.shortfalls[0].available_qty === 5, `Expected 5, got ${r.shortfalls[0].available_qty}`);")
L("  });")
L("  await test('no billing_transaction or dispensed_item written', async () => {")
L("    assert(billingTxns.length === 0 && dispensedItems.length === 0, 'Unexpected writes on failure');")
L("  });")
L("}")
L("")
L("async function scenario5() {")
L("  console.log('\\nScenario 5: Sync path -- canonical service returns insufficient_stock (SS8.3)');")
L("  resetState();")
L("  const BS = await getBillingService();")
L("  const phcId = 'phc-sync'; const medId = 'med-sync-rare';")
L("  batches.push({ id: 'batch-s', phc_id: phcId, medicine_id: medId, remaining_qty: 3, expiry_date: '2027-01-01', minimum_threshold: 2 });")
L("  const client = makeMockClient();")
L("")
L("  const result = await BS.checkout(client, phcId, { client_txn_id: 'sync-txn-001', items: [{ medicine_id: medId, quantity: 100 }] });")
L("")
L("  await test('canonical service returns insufficient_stock', async () => {")
L("    assert(result.outcome === 'insufficient_stock', `Got ${result.outcome}`);")
L("  });")
L("  await test('shortfall qty is correct (available=3, requested=100)', async () => {")
L("    const sf = (result as any).shortfalls[0];")
L("    assert(sf.available_qty === 3, `Expected 3, got ${sf.available_qty}`);")
L("    assert(sf.requested_qty === 100, `Expected 100, got ${sf.requested_qty}`);")
L("  });")
L("}")
L("")
L("async function scenario6() {")
L("  console.log('\\nScenario 6: billing.transaction_completed event emitted');")
L("  resetState();")
L("  const BS = await getBillingService();")
L("  const phcId = 'phc-ev'; const medId = 'med-ev';")
L("  batches.push({ id: 'batch-ev', phc_id: phcId, medicine_id: medId, remaining_qty: 50, expiry_date: '2027-01-01', minimum_threshold: 5 });")
L("  const client = makeMockClient();")
L("")
L("  await BS.checkout(client, phcId, { client_txn_id: 'txn-ev', items: [{ medicine_id: medId, quantity: 10 }] });")
L("  await new Promise<void>((r) => setTimeout(r, 30));")
L("")
L("  await test('billing.transaction_completed event in history', async () => {")
L("    const events = eventBus.getHistory('billing.transaction_completed');")
L("    assert(events.length >= 1, `Expected >=1 event, got ${events.length}`);")
L("    assert(events[0].payload.phc_id === phcId, 'Wrong phc_id in event');")
L("  });")
L("  await test('event payload has transaction_id and item_count', async () => {")
L("    const ev = eventBus.getHistory('billing.transaction_completed')[0];")
L("    assert(typeof ev.payload.transaction_id === 'string', 'Missing transaction_id');")
L("    assert(typeof ev.payload.item_count === 'number', 'Missing item_count');")
L("  });")
L("}")
L("")
L("async function scenario7() {")
L("  console.log('\\nScenario 7: stock.threshold_breached emitted when stock goes CRITICAL');")
L("  resetState();")
L("  const BS = await getBillingService();")
L("  const phcId = 'phc-crit'; const medId = 'med-crit';")
L("  // remaining=10, threshold=20 -> after dispensing 8, remaining=2 which is < threshold => CRITICAL")
L("  batches.push({ id: 'batch-crit', phc_id: phcId, medicine_id: medId, remaining_qty: 10, expiry_date: '2027-01-01', minimum_threshold: 20 });")
L("  const client = makeMockClient();")
L("")
L("  await BS.checkout(client, phcId, { client_txn_id: 'txn-crit', items: [{ medicine_id: medId, quantity: 8 }] });")
L("  await new Promise<void>((r) => setTimeout(r, 30));")
L("")
L("  await test('stock.threshold_breached fired with CRITICAL status', async () => {")
L("    const events = eventBus.getHistory('stock.threshold_breached');")
L("    assert(events.length >= 1, `Expected threshold event`);")
L("    assert(events[0].payload.medicine_id === medId, 'Wrong medicine_id');")
L("    assert(events[0].payload.health_status === 'CRITICAL', `Expected CRITICAL, got ${events[0].payload.health_status}`);")
L("    assert(events[0].payload.triggered_by === 'billing_checkout', 'Wrong triggered_by');")
L("  });")
L("}")
L("")
L("// =================== MAIN ===================")
L("(async () => {")
L("  console.log('=== Billing / FEFO Dispensing Integration Tests ===');")
L("  await scenario1();")
L("  await scenario2();")
L("  await scenario3();")
L("  await scenario4();")
L("  await scenario5();")
L("  await scenario6();")
L("  await scenario7();")
L("  console.log(`\\n${'='.repeat(50)}`);")
L("  if (failed === 0) {")
L("    console.log(`\\u2713 All Billing & FEFO Integration tests PASSED (${passed}/${passed + failed})`);")
L("    process.exit(0);")
L("  } else {")
L("    console.log(`\\u2717 ${failed} test(s) FAILED out of ${passed + failed}`);")
L("    process.exit(1);")
L("  }")
L("})();")

out = '\n'.join(lines)
with open('tests/test_billing_fefo.ts', 'w', encoding='utf-8') as f:
    f.write(out)
print('OK test len=' + str(len(out)))
