lines = []
def L(s): lines.append(s)

L("import { Router, Request, Response } from 'express';")
L("import { requireAuth } from '../../middleware/tenantContext';")
L("import { BillingService, CheckoutInput } from './billingService';")
L("")
L("const router = Router({ mergeParams: true });")
L("")
L("/**")
L(" * POST /api/v1/phc/:phcId/billing/checkout")
L(" * Idempotent FEFO checkout (Architecture SS3.3.1).")
L(" * 409 on insufficient stock; 200 with already_existed:true on duplicate client_txn_id.")
L(" */")
L("router.post('/billing/checkout', requireAuth, async (req: Request, res: Response) => {")
L("  try {")
L("    const { phcId } = req.params;")
L("    const { client_txn_id, patient_ref, dispensed_by_staff_id, items, client_timestamp } = req.body;")
L("")
L("    if (!client_txn_id) {")
L("      res.status(400).json({ error_code: 'MISSING_CLIENT_TXN_ID', message: 'client_txn_id is required for idempotency.' });")
L("      return;")
L("    }")
L("    if (!Array.isArray(items) || items.length === 0) {")
L("      res.status(400).json({ error_code: 'EMPTY_BILLING_ITEMS', message: 'items array must not be empty.' });")
L("      return;")
L("    }")
L("    for (const item of items) {")
L("      if (!item.medicine_id || typeof item.quantity !== 'number' || item.quantity <= 0) {")
L("        res.status(400).json({ error_code: 'INVALID_ITEM', message: 'Each item requires medicine_id and a positive quantity.' });")
L("        return;")
L("      }")
L("    }")
L("")
L("    const input: CheckoutInput = { client_txn_id, patient_ref, dispensed_by_staff_id, items, client_timestamp };")
L("    const result = await BillingService.checkoutRest(phcId, input);")
L("")
L("    if (result.outcome === 'insufficient_stock') {")
L("      res.status(409).json({")
L("        error_code: 'INSUFFICIENT_STOCK',")
L("        message: 'One or more requested medicines cannot be fulfilled.',")
L("        shortfalls: result.shortfalls,")
L("      });")
L("      return;")
L("    }")
L("")
L("    const statusCode = result.already_existed ? 200 : 201;")
L("    res.status(statusCode).json({")
L("      data: {")
L("        transaction_id: result.transaction_id,")
L("        client_txn_id: result.client_txn_id,")
L("        already_existed: result.already_existed,")
L("        total_amount: result.total_amount,")
L("        dispensed_items: result.dispensed_items,")
L("      },")
L("    });")
L("  } catch (err: any) {")
L("    console.error('POST /billing/checkout error', err);")
L("    res.status(500).json({ error_code: 'CHECKOUT_FAILED', message: err.message || 'Internal server error' });")
L("  }")
L("});")
L("")
L("/**")
L(" * GET /api/v1/phc/:phcId/billing/transactions")
L(" * Most recent billing transactions for this PHC (up to 500).")
L(" */")
L("router.get('/billing/transactions', requireAuth, async (req: Request, res: Response) => {")
L("  try {")
L("    const { phcId } = req.params;")
L("    const result = await BillingService.listTransactions(phcId, req.tenantClaims!);")
L("    res.status(200).json(result);")
L("  } catch (err: any) {")
L("    console.error('GET /billing/transactions error', err);")
L("    res.status(500).json({ error_code: 'LIST_FAILED', message: err.message });")
L("  }")
L("});")
L("")
L("/**")
L(" * GET /api/v1/phc/:phcId/billing/transactions/:transactionId")
L(" * Full transaction detail including all dispensed_items.")
L(" */")
L("router.get('/billing/transactions/:transactionId', requireAuth, async (req: Request, res: Response) => {")
L("  try {")
L("    const { phcId, transactionId } = req.params;")
L("    const result = await BillingService.getTransactionDetails(phcId, transactionId, req.tenantClaims!);")
L("    res.status(200).json({ data: result });")
L("  } catch (err: any) {")
L("    const status = err.statusCode || 500;")
L("    res.status(status).json({ error_code: err.message || 'DETAIL_FAILED' });")
L("  }")
L("});")
L("")
L("export default router;")

out = '\n'.join(lines)
with open('src/modules/billing/billingController.ts', 'w', encoding='utf-8') as f:
    f.write(out)
print('OK ctrl len=' + str(len(out)))
